[project]
name = "Jane AI-assistant"
version = "0.1.0"

[tool.ruff]
target-version = "py313"
exclude = [
    "**/*.ipynb",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I"]

[tool.data]
data-dir = "data"
books-subdir = "books"
